export type ServiceStat = { value: string; label: string; sublabel: string };
export type ServiceTool = { icon: string; brand?: boolean; title: string; subtitle: string };
export type ServiceFaq = { q: string; a: string };

export type ServiceData = {
  slug: string;
  title: string;
  breadcrumbLabel: string;
  heroDecoration: "rich" | "medium" | "minimal";
  heroIcon: string;
  heroEyebrow: string;
  heroH1: string[];
  heroDesc: string;
  heroNoteIcon: string;
  heroNote: string;
  stats: [ServiceStat, ServiceStat, ServiceStat, ServiceStat];
  toolsEyebrow: string;
  toolsH2: string;
  tools: [ServiceTool, ServiceTool, ServiceTool, ServiceTool];
  entregasEyebrow: string;
  entregasH2: string[];
  entregasItems: string[];
  entregasVariant: "card" | "image";
  entregasImage?: { src: string; alt: string };
  nextStep?: { title: string; desc: string; cta: string };
  faqH2?: string;
  faq?: ServiceFaq[];
  finalCta: { eyebrow: string; h2: string; desc: string; cta: string };
};

export const services: ServiceData[] = [
  {
    slug: "design-identidade",
    title: "Design e Identidade Visual | Nexo Digital",
    breadcrumbLabel: "Design e Identidade Visual",
    heroDecoration: "rich",
    heroIcon: "fa-palette",
    heroEyebrow: "Design e Identidade Visual",
    heroH1: ["Design que Posiciona", "e Aumenta Valor"],
    heroDesc: "Criamos identidades visuais e materiais que aumentam percepção de valor, autoridade e coerência da sua marca no digital.",
    heroNoteIcon: "fa-circle-dot",
    heroNote: "Sem taxa de setup · Briefing incluso",
    stats: [
      { value: "+300%", label: "Percepção de valor", sublabel: "vs. marcas sem identidade" },
      { value: "5 dias", label: "Entrega média", sublabel: "de identidade visual completa" },
      { value: "12+", label: "Peças entregues", sublabel: "no kit de identidade" },
      { value: "100%", label: "Exclusividade", sublabel: "criações únicas por cliente" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Ferramentas que Utilizamos",
    tools: [
      { icon: "fa-figma", brand: true, title: "Figma", subtitle: "UI & design de sistemas" },
      { icon: "fa-photo-film", title: "Adobe CC", subtitle: "Illustrator, Photoshop, Premiere" },
      { icon: "fa-pen-nib", title: "Canva Pro", subtitle: "Templates e artes rápidas" },
      { icon: "fa-globe", title: "Webflow", subtitle: "Design de páginas e sites" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["Design que Vende antes de Você Falar"],
    entregasItems: [
      "Diagnóstico de marca e briefing estratégico",
      "Logotipo em múltiplas versões e formatos",
      "Paleta de cores e tipografia definidas",
      "Guia de identidade visual completo",
      "Templates de posts para Instagram e LinkedIn",
      "Banners, flyers e materiais offline",
      "Artes para WhatsApp e grupos",
      "Design de checkout e páginas de venda",
      "Criativos para tráfego pago",
      "Peças de lançamento e webinar",
    ],
    entregasVariant: "card",
    nextStep: {
      title: "Sua marca merece um visual que vende",
      desc: "Conte sobre seu negócio e receba uma proposta de identidade visual alinhada ao seu posicionamento.",
      cta: "Solicitar Proposta",
    },
    faqH2: "Dúvidas sobre Design e Identidade Visual",
    faq: [
      { q: "Preciso ter um briefing pronto?", a: "Não. Fazemos o briefing com você antes de começar. Basta trazer referências e nos contar sobre sua empresa." },
      { q: "Quantas revisões estão inclusas?", a: "2 rodadas de revisão por entrega. Revisões extras entram como add-on." },
      { q: "Posso usar os arquivos em qualquer formato?", a: "Sim. Entregamos AI, PDF, PNG, SVG e JPG. Tudo organizado por uso." },
    ],
    finalCta: {
      eyebrow: "Vamos começar",
      h2: "Sua marca merece um visual que vende",
      desc: "Conte sobre seu negócio e receba uma proposta de identidade visual alinhada ao seu posicionamento.",
      cta: "Solicitar Proposta Grátis",
    },
  },
  {
    slug: "crm-funis",
    title: "CRM & Funis de Vendas — Nexo Digital",
    breadcrumbLabel: "CRM & Funis de Vendas",
    heroDecoration: "rich",
    heroIcon: "fa-filter",
    heroEyebrow: "CRM & Funis de Vendas",
    heroH1: ["Funis que", "Fecham Negócios"],
    heroDesc: "Implementamos e otimizamos CRMs com funis personalizados que organizam o processo de vendas, qualificam leads automaticamente e aumentam a taxa de fechamento.",
    heroNoteIcon: "fa-trophy",
    heroNote: "+31% taxa de fechamento média",
    stats: [
      { value: "+31%", label: "Taxa de fechamento", sublabel: "média nos clientes" },
      { value: "-40%", label: "Tempo no funil", sublabel: "do lead à venda" },
      { value: "100%", label: "Rastreabilidade", sublabel: "de cada lead no pipeline" },
      { value: "5h", label: "Economizadas/semana", sublabel: "por vendedor com automação" },
    ],
    toolsEyebrow: "CRMs que Implementamos",
    toolsH2: "Especialistas em",
    tools: [
      { icon: "fa-hubspot", brand: true, title: "HubSpot", subtitle: "CRM + Marketing Hub" },
      { icon: "fa-diagram-project", title: "Pipedrive", subtitle: "Pipeline visual & automações" },
      { icon: "fa-bullseye", title: "RD Station", subtitle: "Leads & oportunidades" },
      { icon: "fa-salesforce", brand: true, title: "Salesforce", subtitle: "Enterprise & customizações" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["CRM que Funciona como", "Máquina de Conversão"],
    entregasItems: [
      "Implementação e configuração completa do CRM",
      "Criação de funil personalizado por produto/serviço",
      "Lead scoring automático por comportamento",
      "Automações de tarefas e alertas para vendedores",
      "Integração com formulários, ads e e-mail",
      "Dashboard de performance comercial",
      "Treinamento do time de vendas",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1504868584819-f8e8b4b6d7e3?w=700&q=80", alt: "CRM Dashboard" },
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Seu CRM Precisa Trabalhar por Você",
      desc: "Auditamos seu processo comercial e mostramos como estruturar um funil que fecha mais, com menos esforço manual.",
      cta: "Solicitar Diagnóstico Grátis",
    },
  },
  {
    slug: "automacao",
    title: "Automação de Marketing — Nexo Digital",
    breadcrumbLabel: "Automação de Marketing",
    heroDecoration: "rich",
    heroIcon: "fa-robot",
    heroEyebrow: "Automação de Marketing",
    heroH1: ["Venda enquanto", "você dorme"],
    heroDesc: "Construímos fluxos de automação que nutrem, qualificam e convertem leads 24h por dia — sem intervenção manual e com custo de aquisição em queda constante.",
    heroNoteIcon: "fa-bolt",
    heroNote: "Fluxos ao vivo em até 15 dias",
    stats: [
      { value: "300%", label: "Mais leads MQL", sublabel: "em 90 dias com nurturing" },
      { value: "-55%", label: "Redução de CAC", sublabel: "com lead scoring automático" },
      { value: "24/7", label: "Funil operacional", sublabel: "sem depender de equipe" },
      { value: "3x", label: "Velocidade no funil", sublabel: "do lead à venda" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Plataformas que Dominamos",
    tools: [
      { icon: "fa-hubspot", brand: true, title: "HubSpot", subtitle: "Workflows & CRM completo" },
      { icon: "fa-bullseye", title: "RD Station", subtitle: "Automação & lead management" },
      { icon: "fa-bolt", title: "Make / n8n", subtitle: "Integrações & webhooks" },
      { icon: "fa-envelope", title: "ActiveCampaign", subtitle: "E-mail automation & scoring" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["Automação que Escala", "seu Processo de Vendas"],
    entregasItems: [
      "Mapeamento e modelagem do funil de automação",
      "Lead scoring baseado em comportamento e perfil",
      "Sequências de nutrição por e-mail e WhatsApp",
      "Integração entre CRM, ads e ferramentas de vendas",
      "Automação de tarefas e alertas para o time comercial",
      "Fluxos de reengajamento e reativação de base",
      "Webhooks e integrações via Make / n8n",
      "Relatório mensal com análise de performance dos fluxos",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=700&q=80", alt: "Marketing Automation" },
    faqH2: "Dúvidas sobre Automação",
    faq: [
      { q: "Já tenho um CRM. Vocês conseguem integrar?", a: "Sim. Trabalhamos com HubSpot, Pipedrive, RD Station, Salesforce e outros via API ou Make/n8n. Avaliamos seu stack atual antes de propor qualquer mudança." },
      { q: "Preciso ter grande base de leads para começar?", a: "Não. Construímos automações que já capturam e nutrem desde o zero. O ideal é ter ao menos um canal de captação (anúncios, formulário, WhatsApp) funcionando para que os fluxos comecem a trabalhar." },
      { q: "Em quanto tempo os fluxos ficam prontos?", a: "Os primeiros fluxos principais ficam ao vivo em até 15 dias úteis após o kick-off. Fluxos mais complexos com múltiplas integrações podem levar de 30 a 45 dias." },
    ],
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Automatize. Escale. Repita.",
      desc: "Conte como é seu processo de vendas hoje. Nossa equipe mapeia as automações certas para o seu negócio.",
      cta: "Solicitar Diagnóstico Grátis",
    },
  },
  {
    slug: "edicao-video",
    title: "Edição de Vídeo | Nexo Digital",
    breadcrumbLabel: "Edição de Vídeo",
    heroDecoration: "rich",
    heroIcon: "fa-video",
    heroEyebrow: "Edição de Vídeo",
    heroH1: ["Você Grava.", "A Gente Transforma."],
    heroDesc: "Editamos seus vídeos com qualidade profissional: cortes precisos, legendas dinâmicas e identidade visual aplicada em cada frame.",
    heroNoteIcon: "fa-circle-dot",
    heroNote: "Entrega em até 48h · Sem filmagem",
    stats: [
      { value: "48h", label: "Entrega média", sublabel: "por vídeo editado" },
      { value: "4K", label: "Suporte", sublabel: "qualquer resolução" },
      { value: "100%", label: "Exclusividade", sublabel: "sem templates genéricos" },
      { value: "3+", label: "Plataformas", sublabel: "formatos adaptados por entrega" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Stack de Edição que Usamos",
    tools: [
      { icon: "fa-film", title: "CapCut Pro", subtitle: "Reels e conteúdo rápido" },
      { icon: "fa-clapperboard", title: "Premiere Pro", subtitle: "Edição profissional" },
      { icon: "fa-circle-play", title: "DaVinci Resolve", subtitle: "Colorização e correção" },
      { icon: "fa-wand-magic-sparkles", title: "After Effects", subtitle: "Motion e animações" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["Vídeo Editado, Pronto pra Publicar"],
    entregasItems: [
      "Reels editados com cortes dinâmicos",
      "Shorts e vídeos para TikTok",
      "Vídeos de anúncio (15s, 30s, 60s)",
      "Cortes de aulas e gravações longas",
      "Lives e podcasts editados com cortes",
      "Vídeos de depoimento e prova social",
      "Legendas dinâmicas e animadas",
      "Aplicação de logo, cores e identidade visual",
    ],
    entregasVariant: "card",
    nextStep: {
      title: "Transforme seus vídeos em conteúdo que engaja",
      desc: "Envie seu material bruto e receba um vídeo editado, com identidade aplicada e pronto para publicar.",
      cta: "Solicitar Proposta",
    },
    faqH2: "Dúvidas sobre Edição de Vídeo",
    faq: [
      { q: "Em qual formato devo enviar o vídeo bruto?", a: "Qualquer formato aceito: MP4, MOV, AVI, MKV. Quanto maior a qualidade original, melhor o resultado final." },
      { q: "Vocês captam o vídeo?", a: "Não. A captura é responsabilidade do cliente. Só editamos o material que você envia." },
      { q: "Quantas revisões estão inclusas?", a: "1 rodada de revisão por vídeo. Revisões adicionais entram como add-on." },
    ],
    finalCta: {
      eyebrow: "Vamos começar",
      h2: "Transforme seus vídeos em conteúdo que engaja",
      desc: "Envie seu material bruto e receba um vídeo editado, com identidade aplicada e pronto para publicar.",
      cta: "Solicitar Proposta Grátis",
    },
  },
  {
    slug: "email-marketing",
    title: "E-mail Marketing — Nexo Digital",
    breadcrumbLabel: "E-mail Marketing",
    heroDecoration: "rich",
    heroIcon: "fa-envelope-open-text",
    heroEyebrow: "E-mail Marketing",
    heroH1: ["E-mails que", "Abrem e Convertem"],
    heroDesc: "Construímos sequências estratégicas de e-mail que nutrem relacionamento, reativam base dormida e geram receita previsível — o canal com maior ROI do marketing digital.",
    heroNoteIcon: "fa-chart-line",
    heroNote: "R$42 de retorno por R$1 investido",
    stats: [
      { value: "35%", label: "Taxa de abertura", sublabel: "média nas campanhas" },
      { value: "8%", label: "CTR médio", sublabel: "acima do mercado (2-3%)" },
      { value: "R$42", label: "ROI por R$1", sublabel: "o canal de maior retorno" },
      { value: "90d", label: "Para reativar base", sublabel: "com fluxo de win-back" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Plataformas que Operamos",
    tools: [
      { icon: "fa-mailchimp", brand: true, title: "Mailchimp", subtitle: "Campanhas & automações" },
      { icon: "fa-envelope", title: "ActiveCampaign", subtitle: "Sequências inteligentes" },
      { icon: "fa-at", title: "Klaviyo", subtitle: "E-commerce & segmentação" },
      { icon: "fa-hubspot", brand: true, title: "HubSpot", subtitle: "CRM + e-mail integrado" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["E-mail Marketing que", "Gera Receita Real"],
    entregasItems: [
      "Auditoria e higienização da base de contatos",
      "Sequências de boas-vindas e onboarding",
      "Fluxos de nutrição segmentados por perfil",
      "Campanhas sazonais e de lançamento",
      "Testes A/B de assunto, copy e CTA",
      "Fluxo de carrinho abandonado (e-commerce)",
      "Win-back para base inativa",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1563986768609-322da13575f3?w=700&q=80", alt: "Email Marketing" },
    faqH2: "Dúvidas sobre E-mail Marketing",
    faq: [
      { q: "Preciso ter uma base grande para começar?", a: "Não. Trabalhamos desde bases de 500 contatos. O importante é qualidade, não quantidade. Também criamos estratégias para crescer a base de forma orgânica enquanto otimizamos os fluxos existentes." },
      { q: "Como evitam que os e-mails caiam no spam?", a: "Configuramos autenticação SPF, DKIM e DMARC, fazemos aquecimento de domínio gradual, higienizamos a lista periodicamente e monitoramos as métricas de entregabilidade em tempo real." },
    ],
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Transforme sua Base em Receita",
      desc: "Auditamos sua situação atual e projetamos o potencial de receita da sua base de contatos.",
      cta: "Solicitar Auditoria Grátis",
    },
  },
  {
    slug: "seo-conteudo",
    title: "SEO & Conteúdo — Nexo Digital",
    breadcrumbLabel: "SEO & Conteúdo",
    heroDecoration: "rich",
    heroIcon: "fa-magnifying-glass-chart",
    heroEyebrow: "SEO & Conteúdo",
    heroH1: ["Tráfego Orgânico que", "Cresce Todo Mês"],
    heroDesc: "Construímos autoridade de marca e presença no Google com estratégia de conteúdo orientada a busca, SEO técnico e link building — o único canal que aumenta de valor enquanto você dorme.",
    heroNoteIcon: "fa-arrow-trend-up",
    heroNote: "+250% tráfego orgânico médio em 6 meses",
    stats: [
      { value: "+250%", label: "Tráfego orgânico", sublabel: "crescimento médio em 6 meses" },
      { value: "Top 3", label: "Posição no Google", sublabel: "para keywords estratégicas" },
      { value: "12+", label: "Artigos por mês", sublabel: "otimizados para SEO" },
      { value: "6m", label: "Para resultados sólidos", sublabel: "com consistência" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Stack de SEO que Usamos",
    tools: [
      { icon: "fa-google", brand: true, title: "Google Search Console", subtitle: "Performance & indexação" },
      { icon: "fa-magnifying-glass", title: "Ahrefs", subtitle: "Backlinks & keywords" },
      { icon: "fa-chart-pie", title: "SEMrush", subtitle: "Competidores & auditorias" },
      { icon: "fa-wave-square", title: "SurferSEO", subtitle: "Otimização on-page" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["SEO & Conteúdo que", "Gera Autoridade Real"],
    entregasItems: [
      "Auditoria técnica completa do site",
      "Pesquisa de palavras-chave estratégicas",
      "Produção de artigos otimizados para SEO",
      "Otimização de páginas de serviço e produto",
      "Link building com sites de autoridade",
      "SEO técnico: Core Web Vitals, schema, sitemap",
      "Relatório mensal de posições e tráfego",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1432888622747-4eb9a8efeb07?w=700&q=80", alt: "SEO & Conteúdo" },
    faqH2: "Dúvidas sobre SEO",
    faq: [
      { q: "Em quanto tempo o SEO gera resultados?", a: "SEO é um investimento de médio prazo. As primeiras melhorias técnicas aparecem em 30-60 dias. Resultados expressivos de tráfego e posicionamento normalmente se consolidam entre o 4º e 6º mês de trabalho consistente." },
      { q: "Vocês garantem ranking #1 no Google?", a: "Ninguém pode garantir posição específica pois os algoritmos do Google são dinâmicos. O que garantimos é trabalho técnico de qualidade, conteúdo relevante e backlinks de autoridade que aumentam significativamente as chances de rankear nas primeiras posições." },
    ],
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Comece a Crescer no Orgânico",
      desc: "Auditamos seu site gratuitamente e mostramos as maiores oportunidades de SEO que você está perdendo hoje.",
      cta: "Pedir Auditoria SEO Grátis",
    },
  },
  {
    slug: "sites-paginas",
    title: "Sites, Páginas e Checkouts | Nexo Digital",
    breadcrumbLabel: "Sites, Páginas e Checkouts",
    heroDecoration: "rich",
    heroIcon: "fa-globe",
    heroEyebrow: "Sites, Páginas e Checkouts",
    heroH1: ["Páginas que Conduzem", "e Convertem"],
    heroDesc: "Desenvolvemos sites, páginas de captura, venda e checkout com copy estratégica e estrutura pensada para transformar visita em cliente.",
    heroNoteIcon: "fa-circle-dot",
    heroNote: "Copy inclusa · Mobile-first · Sem mensalidade",
    stats: [
      { value: "+40%", label: "Conversão média", sublabel: "vs. páginas genéricas" },
      { value: "7 dias", label: "Entrega", sublabel: "para páginas simples" },
      { value: "100%", label: "Responsivo", sublabel: "mobile-first em tudo" },
      { value: "Copy", label: "Inclusa", sublabel: "sem custo adicional" },
    ],
    toolsEyebrow: "Ferramentas",
    toolsH2: "Plataformas que Dominamos",
    tools: [
      { icon: "fa-globe", title: "Webflow", subtitle: "Sites e landing pages" },
      { icon: "fa-wordpress", brand: true, title: "WordPress", subtitle: "Blogs e sites institucionais" },
      { icon: "fa-code", title: "HTML/CSS", subtitle: "Estático e alto desempenho" },
      { icon: "fa-shop", title: "Hotmart/Kiwify", subtitle: "Checkout e área de membros" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["Estrutura de Página que Vira Receita"],
    entregasItems: [
      "Site institucional completo",
      "Página de captura com copy estratégica",
      "Página de vendas com argumentação de oferta",
      "Página de obrigado e upsell",
      "Estrutura de webinar e evento online",
      "Lista de espera e lançamento",
      "Checkout e order bump configurados",
      "Copy e estrutura completa de todas as seções",
    ],
    entregasVariant: "card",
    nextStep: {
      title: "Sua empresa merece uma página que trabalha por você",
      desc: "Conte sobre seu negócio e receba uma proposta de página ou site com estrutura, copy e design inclusos.",
      cta: "Solicitar Proposta",
    },
    faqH2: "Dúvidas sobre Sites, Páginas e Checkouts",
    faq: [
      { q: "Qual plataforma vocês usam?", a: "Depende do projeto. Usamos Webflow, WordPress ou HTML estático conforme a necessidade e orçamento." },
      { q: "Vocês fazem a copy?", a: "Sim. A copy está inclusa no escopo de todas as páginas." },
      { q: "E a hospedagem?", a: "Indicamos e configuramos a hospedagem ideal, mas o custo mensal é por conta do cliente." },
    ],
    finalCta: {
      eyebrow: "Vamos começar",
      h2: "Sua empresa merece uma página que trabalha por você",
      desc: "Conte sobre seu negócio e receba uma proposta de página ou site com estrutura, copy e design inclusos.",
      cta: "Solicitar Proposta Grátis",
    },
  },
  {
    slug: "social-media",
    title: "Social Media — Nexo Digital",
    breadcrumbLabel: "Social Media",
    heroDecoration: "rich",
    heroIcon: "fa-share-nodes",
    heroEyebrow: "Social Media",
    heroH1: ["Presença que", "Constrói Autoridade"],
    heroDesc: "Criamos, publicamos e gerenciamos seu conteúdo nas redes sociais com estratégia editorial que gera engajamento, seguidores qualificados e oportunidades de venda.",
    heroNoteIcon: "fa-calendar",
    heroNote: "Primeiros posts em 7 dias",
    stats: [
      { value: "+180%", label: "Engajamento médio", sublabel: "nos primeiros 60 dias" },
      { value: "30+", label: "Posts por mês", sublabel: "feed + stories + reels" },
      { value: "+12k", label: "Seguidores/mês", sublabel: "crescimento orgânico médio" },
      { value: "4h", label: "Tempo de resposta", sublabel: "gerenciamento de DMs" },
    ],
    toolsEyebrow: "Redes Sociais",
    toolsH2: "Onde Gerenciamos sua Marca",
    tools: [
      { icon: "fa-instagram", brand: true, title: "Instagram", subtitle: "Feed, Reels, Stories" },
      { icon: "fa-linkedin", brand: true, title: "LinkedIn", subtitle: "Conteúdo B2B & pessoal" },
      { icon: "fa-tiktok", brand: true, title: "TikTok", subtitle: "Vídeos virais & trends" },
      { icon: "fa-youtube", brand: true, title: "YouTube", subtitle: "SEO em vídeo & Shorts" },
    ],
    entregasEyebrow: "O Que Entregamos",
    entregasH2: ["Conteúdo Estratégico", "que Gera Negócio"],
    entregasItems: [
      "Calendário editorial mensal alinhado à estratégia",
      "Produção de copy e briefing para todos os posts",
      "Gestão de comentários e mensagens diretas",
      "Estratégia de hashtags e SEO nas redes",
      "Análise de concorrência e benchmarking",
      "Relatório mensal de performance por rede",
      "Monitoramento de menções e crises de marca",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=700&q=80", alt: "Social Media" },
    faqH2: "Dúvidas sobre Social Media",
    faq: [
      { q: "Quem produz o design dos posts?", a: "No plano Scale e Pro, nossa equipe entrega briefings completos de arte + copy. Para produção gráfica full, trabalhamos junto com seu designer ou parceiro criativo." },
      { q: "Vocês fazem aprovação de conteúdo?", a: "Sim. Todo conteúdo passa por aprovação do cliente antes de publicar. Usamos ferramentas de gestão colaborativa onde você visualiza, comenta e aprova posts pelo celular." },
    ],
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Sua Marca Merece Mais Atenção",
      desc: "Conte-nos sobre seu negócio e desbloqueie uma estratégia de social media sob medida.",
      cta: "Solicitar Proposta Grátis",
    },
  },
  {
    slug: "trafego-pago",
    title: "Tráfego Pago — Nexo Digital",
    breadcrumbLabel: "Tráfego Pago",
    heroDecoration: "rich",
    heroIcon: "fa-chart-bar",
    heroEyebrow: "Tráfego Pago",
    heroH1: ["Anúncios que Convertem", "de Verdade"],
    heroDesc: "Gerenciamos campanhas em Google, Meta, TikTok e LinkedIn com foco em ROAS real — não em impressões. Cada real investido é rastreado até a venda.",
    heroNoteIcon: "fa-shield-halved",
    heroNote: "Sem taxa de setup · Sem fidelidade",
    stats: [
      { value: "7x", label: "ROAS médio", sublabel: "nas campanhas ativas" },
      { value: "-42%", label: "Redução de CAC", sublabel: "média nos primeiros 90 dias" },
      { value: "R$47M", label: "Em mídia gerenciada", sublabel: "desde 2016" },
      { value: "48h", label: "Para campanhas ao vivo", sublabel: "após aprovação do briefing" },
    ],
    toolsEyebrow: "Plataformas",
    toolsH2: "Onde Gerenciamos Seus Anúncios",
    tools: [
      { icon: "fa-google", brand: true, title: "Google Ads", subtitle: "Search, Display, Pmax, YouTube" },
      { icon: "fa-meta", brand: true, title: "Meta Ads", subtitle: "Facebook, Instagram, Advantage+" },
      { icon: "fa-tiktok", brand: true, title: "TikTok Ads", subtitle: "Spark Ads, TopFeed, Retargeting" },
      { icon: "fa-linkedin", brand: true, title: "LinkedIn Ads", subtitle: "Sponsored, Message, Retargeting" },
    ],
    entregasEyebrow: "O Que Está Incluso",
    entregasH2: ["Gestão Completa,", "do Pixel à Conversão"],
    entregasItems: [
      "Configuração e auditoria de pixels e tags (GTM)",
      "Criação de públicos e segmentações avançadas",
      "Produção e teste de criativos (copy + arte)",
      "Gestão de lances e orçamento em tempo real",
      "Relatórios semanais com dashboard ao vivo",
      "Reunião quinzenal de performance e estratégia",
      "Testes A/B contínuos em criativos e ofertas",
      "Remarketing e lookalike avançados",
    ],
    entregasVariant: "image",
    entregasImage: { src: "https://images.unsplash.com/photo-1460925895917-afdab827c52f?w=700&q=80", alt: "Tráfego Pago Dashboard" },
    faqH2: "Dúvidas sobre Tráfego Pago",
    faq: [
      { q: "Qual o investimento mínimo em mídia?", a: "Recomendamos mínimo de R$3.000/mês em verba de mídia (separado da taxa de gestão). Para e-commerce, o ideal é R$5.000+. Isso garante volume suficiente para os algoritmos otimizarem." },
      { q: "Quanto tempo para ver resultados?", a: "Primeiras campanhas ao ar em até 48h. Resultados iniciais aparecem na 2ª semana. A otimização real acontece entre a 3ª e 6ª semana, quando os algoritmos têm dados suficientes para aprendizado." },
      { q: "Quem cria os criativos dos anúncios?", a: "Nossa equipe cria textos (copy) para todos os anúncios. Para artes visuais, trabalhamos junto com seu time criativo ou entregamos briefs detalhados. Para projetos Pro, incluímos produção de criativo completo." },
    ],
    finalCta: {
      eyebrow: "Próximo Passo",
      h2: "Pronto para Escalar Suas Campanhas?",
      desc: "Agende um diagnóstico gratuito. Analisamos suas campanhas atuais e mostramos exatamente onde há desperdício e oportunidade.",
      cta: "Quero Meu Diagnóstico Grátis",
    },
  },
];

export function getServiceBySlug(slug: string) {
  return services.find((s) => s.slug === slug);
}
